name: Deploy TITLE-NOMICS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  NODE_VERSION: 20
  PYTHON_VERSION: 3.11
  CDK_VERSION: 2.204.0

jobs:
  build:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install backend deps & lint
        run: |
          cd cdk
          pip install -r requirements.txt
          python -m py_compile *.py

      - name: Install frontend deps & test
        run: |
          cd frontend
          npm ci
          npm run test -- --watchAll=false --passWithNoTests

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install CDK CLI
        run: npm install -g aws-cdk@${{ env.CDK_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install CDK Python deps
        run: |
          cd cdk
          pip install -r requirements.txt

      - name: CDK Bootstrap (once per account/region)
        run: cdk bootstrap --require-approval never
        working-directory: cdk

      - name: Deploy Backend (CDK)
        id: backend
        run: |
          cdk deploy BedrockDiyAuthStack --require-approval never --outputs-file ../backend-outputs.json
        working-directory: cdk

      - name: Extract API URL
        id: geturl
        run: |
          API_URL=$(cat backend-outputs.json | jq -r '.BedrockDiyAuthStack.ApiGatewayUrl')
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT

      - name: Build Frontend
        env:
          REACT_APP_API_URL: ${{ steps.geturl.outputs.api_url }}
          CI: false
        run: |
          cd frontend
          echo "REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}" > .env.production
          npm ci
          npm run build

      - name: Deploy Frontend (CDK)
        run: |
          cdk deploy FrontendStack --require-approval never --outputs-file ../frontend-outputs.json
        working-directory: cdk

      - name: Show Outputs
        run: |
          FRONTEND_URL=$(cat frontend-outputs.json | jq -r '.FrontendStack.WebsiteURL')
          echo "Frontend URL: $FRONTEND_URL"
          echo "API URL: ${{ steps.geturl.outputs.api_url }}"
